openapi: 3.0.0
info:
  title: Search API
  version: 1.0.0
  description: API documentation for search

servers:
  - url: /api/search
    description: API endpoint

paths:
  /content/:
    get:
      summary: Hybrid search across content
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
        - in: query
          name: encounter_id
          schema:
            type: integer
        - in: query
          name: content_type
          schema:
            type: array
            items:
              type: string
              enum: [encounter, transcript, soap, checklist, notes]
        - in: query
          name: date_from
          schema:
            type: string
            format: date
        - in: query
          name: date_to
          schema:
            type: string
            format: date
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: page_size
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /suggestions/:
    get:
      summary: Get search suggestions
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200': { description: Success }
        '400': { description: Bad Request }
  /analytics/:
    get:
      summary: Get search analytics
      parameters:
        - in: query
          name: days
          schema:
            type: integer
      responses:
        '200': { description: Success }
        '400': { description: Bad Request }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

