openapi: 3.0.0
info:
  title: Notifications API
  version: 1.0.0
  description: API documentation for notifications

servers:
  - url: /api/notifications
    description: API endpoint

paths:
  /send/:
    post:
      summary: Send notification
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notification_type:
                  type: string
                  enum: [sms, email, push, in_app]
                title:
                  type: string
                content:
                  type: string
                priority:
                  type: string
                  enum: [low, normal, high, urgent]
                scheduled_for:
                  type: string
                  format: date-time
                metadata:
                  type: object
              required: [notification_type, title, content]
      responses:
        200:
          description: Queued
        400:
          description: Validation error
        401:
          description: Unauthorized
        429:
          description: Rate limit exceeded
        500:
          description: Internal error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

