# Generated by Django 5.2.5 on 2025-08-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('encounter', 'Encounter'), ('transcript', 'Transcript'), ('soap', 'SOAP Note'), ('checklist', 'Checklist'), ('notes', 'Clinical Notes')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('search_vector', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('metadata_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_content', to='encounters.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('filters', models.JSONField(default=dict)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('snippet', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.searchablecontent')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_results', to='search.searchquery')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['encounter', 'content_type'], name='search_sear_encount_624c78_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['content_type', 'content_id'], name='search_sear_content_d8afbe_idx'),
        ),
        migrations.AddIndex(
            model_name='searchablecontent',
            index=models.Index(fields=['created_at'], name='search_sear_created_153b55_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchablecontent',
            constraint=models.UniqueConstraint(fields=('encounter', 'content_type', 'content_id'), name='uniq_search_encounter_contenttype_contentid'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', 'created_at'], name='search_sear_user_id_2836be_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['created_at'], name='search_sear_created_819524_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['query', 'rank'], name='search_sear_query_i_d2c62a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['relevance_score'], name='search_sear_relevan_b3c1fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(fields=('query', 'content'), name='uniq_query_content'),
        ),
    ]
